

server:
  port: 8080

###Cache
app:
  cache:
    ttl: 300
###Database related
spring:
  profiles:
    active: mem-db
  main:
    banner-mode: off
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console